Cats 1661
ndrmc/cats-web pull request #179
Opened 2017-07-06 11:34 UTC by dawitd

2017-07-06 12:04 UTC, yareda commented on app/views/receipts/_form.html.erb
>    <script type="text/javascript">
Can we move script below this line to corresponding *.js file? This view is very cluttered and difficult to navigate through.

2017-07-06 12:05 UTC, yareda commented on app/views/receipts/_form.html.erb
>    <script type="text/javascript">
@dawitd check if moving to it's own *.js file a better option.

2017-07-06 12:06 UTC, yareda commented on app/views/receipts/_form.html.erb
> +          toastr.error("You need to at least add one commodity.");
@dawitd rephrase error message to -> "You are required to add at one commodity to receive"

2017-07-06 12:08 UTC, yareda requested changes
@dawitd Not sure why we need to change the form to submit over ajax call!

2017-07-07 08:31 UTC, dawitd commented on app/views/receipts/_form.html.erb
>    <script type="text/javascript">
I have moved the pure js scripts to a separate file - receipt.js file. we can not move all scripts to a js file as there are server side scripts.

2017-07-12 06:55 UTC, yareda commented
@nathnael please provide your review and approval

2017-07-12 09:14 UTC, nathnael commented
@dawitd 
Reviews:
1. Unit conversion not handled
2. Received value is negative
3. When I receive "Received" decreased & "Remaining" increased. May be it's because the "Received" value is negative

2017-07-14 06:36 UTC, dawitd commented
In testing the unit issue - make sure that you have updated uom_type and ration fields of the unit_of_measurement table in relation to the reference unit.

2017-07-14 09:47 UTC, nathnael approved these changes

2017-07-17 06:27 UTC, yareda approved these changes

2017-07-17 06:27 UTC, merged