add bid detail information- transporter quots
ndrmc/cats-web pull request #232
Opened 2017-08-18 06:08 UTC by dawitd

2017-08-18 10:56 UTC, nathnael approved these changes

2017-09-04 08:06 UTC, yareda requested changes

2017-09-04 08:06 UTC, yareda commented on app/controllers/bids_controller.rb
>      (13..spreadsheet.last_row).each do |i|
@nathnael what's special about the number 13? what does it stand for? would help to add comment to explain what it is.

2017-09-04 08:06 UTC, yareda commented on app/controllers/bids_controller.rb
> +         if row[5].is_a?( Numeric) &&  row[5] >= 0 && !warehouse_selection.nil?
@nathnael again what does row[5] stand for? what is it? why do we have to use a fixed field index?

2017-09-05 07:32 UTC, nathnael reviewed
@yareda  Replaced hard-coded values by variables

2017-09-05 12:06 UTC, yareda approved these changes

2017-09-05 12:06 UTC, merged