Move ft status to its detail page
ndrmc/cats-web pull request #236
Opened 2017-08-18 09:03 UTC by nathnael

2017-08-22 06:33 UTC, dawitd approved these changes

2017-09-04 08:59 UTC, yareda requested changes

2017-09-04 08:59 UTC, yareda commented on app/models/framework_tender.rb
>       def self.get_index(status)
@nathnael not sure why we're juggling with strings and symbols? What's the purpose of converting strings into symbols?

2017-09-05 08:30 UTC, nathnael commented
@yareda Removed confusing getIndex method in FT model

2017-09-05 12:11 UTC, yareda approved these changes

2017-09-05 12:18 UTC, merged