New TR Implemented new TR pop-up window and filter view with operation
ndrmc/cats-web pull request #251
Opened 2017-08-22 14:18 UTC by nathnael

2017-08-23 12:41 UTC, dawitd approved these changes

2017-09-04 09:48 UTC, yareda commented
Cant we use FontAwesome animations rather than adding an external resource (app/assets/images/loading-gif-15.gif)?

2017-09-04 09:52 UTC, yareda requested changes

2017-09-04 09:52 UTC, yareda commented on db/schema.rb
> +  create_table "transport_requisition_details", force: :cascade do |t|
@nathnael @dawitd what's the difference between tranport_requisition_items and transport_requisition_details?

2017-09-05 09:13 UTC, nathnael commented
@yareda Removed unused loading image and removed TR details from schema

2017-09-06 05:57 UTC, yareda approved these changes

2017-09-06 05:57 UTC, merged