Cats 1560
ndrmc/cats-web pull request #33
Opened 2017-03-02 13:58 UTC by getbez

2017-03-02 14:18 UTC, asuraphel requested changes
@getbez I saw some discrepancies with some of the files. Please handle them.

2017-03-02 14:18 UTC, asuraphel commented on app/assets/javascripts/regional_request.js
> +// All this logic will automatically be available in application.js.
This seems to be added by mistake...

2017-03-02 14:18 UTC, asuraphel commented on app/controllers/receipts_controller.rb
> +
Beza, I did this feature as well but it's showing as new. What went wrong? :)

2017-03-03 06:48 UTC, getbez reviewed
@asuraphel  I have reviewed this commit again and no current code has been affected. Most changes are due to added modules. The others are files i have been working with. The two files you mentioned were shown because of merging after reseting my HEAD to the last develop verison.

2017-03-03 06:48 UTC, getbez commented on app/assets/javascripts/regional_request.js
> +// All this logic will automatically be available in application.js.
I had to recover my repo after a sudden corruption. This seems to have come from your commit 
[https://github.com/fmip/cats-web/commit/1c24bfcac735b967fb615362f08f021c5dafee9a](url) . We can remove the comments. Same reason for your other comment.

2017-03-06 08:10 UTC, asuraphel approved these changes

2017-03-06 08:11 UTC, merged