Hubs and stores
ndrmc/cats-web pull request #7
Opened 2016-11-21 13:53 UTC by getbez

here are the model changes and migrations for warehouse and hubs. (remaining work on location and some clean-up for views)

2016-11-22 08:57 UTC, asuraphel requested changes
Please remove schema.rb from .gitignore

2016-11-22 08:57 UTC, asuraphel commented on .gitignore
> +/db/schema.rb
http://stackoverflow.com/questions/6450263/what-is-the-right-approach-to-deal-with-rails-db-schema-rb-file-in-git

2016-11-23 05:28 UTC, getbez commented on .gitignore
> +/db/schema.rb
good. I did that since it's generated and u guys suggested we ignore it last time. it seems like that's not a good idea after all.

2016-11-23 05:36 UTC, getbez commented
have resolved conflicts.

2016-11-23 10:58 UTC, merged